package MODEL;
/* Generated by Together */

/**
 * For a description of Regular visitors, follow hyperlink to the Administration use case for issuing a new Regular visitor permit.
 * @url element://model:project::PACSUS/design:node:::jgri5gkuaa1f5-48hzfp
 */
public class Regular_visitor_permit extends Permit {
    /**
     * The name of the University member hosting the visit. 
     */
    private String hostName;

    /**
     * The date that the visit starts - entry will not be allowed before this date.
     * @label Starting on
     * @clientCardinality 1
     * @supplierCardinality 1 
     * @link aggregation
     * @directed
     */
    private Date_ Start_Date;

    /**
     * The date that the visit ends - entry will not be allowed after this date.
     * @label Ending on
     * @clientCardinality 1
     * @supplierCardinality 1 
     * @link aggregation
     * @directed
     */
    private Date_ End_Date;
    
	/*
	 * public Regular_visitor_permit( String x) { this.permitHolder=x; hostName=x; }
	 */
}
